# Generated by Django 3.2.9 on 2022-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0002_staticdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochuresections',
            name='brochure_image',
            field=models.ImageField(null=True, upload_to='AHBrochureSections'),
        ),
        migrations.AlterField(
            model_name='broucher',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='AHBookpdf'),
        ),
        migrations.AlterField(
            model_name='coinsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AHCoinSection'),
        ),
        migrations.AlterField(
            model_name='earningmodel',
            name='description_link',
            field=models.FileField(blank=True, null=True, upload_to='AHEarningModel'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='dp_list',
            field=models.ImageField(upload_to='AHORDImage'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='refer_earn',
            field=models.ImageField(upload_to='AHORDImage'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='view_all_offer',
            field=models.ImageField(upload_to='AHORDImage'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AHProductImages'),
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='section_image',
            field=models.ImageField(blank=True, null=True, upload_to='AHSectionImages'),
        ),
        migrations.AlterField(
            model_name='tagname',
            name='tagImage',
            field=models.ImageField(blank=True, null=True, upload_to='AHCategoryImages'),
        ),
    ]
