# Generated by Django 3.2.9 on 2022-06-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0003_auto_20220618_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiondata',
            name='title',
            field=models.CharField(choices=[('Why to use', 'Why to use'), ('Demo Videos', 'Demo Videos'), ('Business Opportunity', 'Business Opportunity'), ('Training Videos', 'Training Videos'), ('Motivational Videos', 'Motivational Videos'), ('Success Stories', 'Success Stories'), ('Testimonial Videos', 'Testimonial Videos'), ('About Amulya Herbal', 'About Amulya Herbal'), ('Become a Partner', 'Become a Partner'), ('Previous Events', 'Previous Events'), ('Upcoming Events', 'Upcoming Events'), ('Book Ticket', 'Book Ticket'), ('Broucher', 'Broucher'), ('Earning Model', 'Earning Model')], max_length=100, unique=True),
        ),
    ]
