# Generated by Django 3.2.9 on 2022-07-07 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amulyaHerbal', '0005_cpaleadurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('required_product', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amulyaHerb_product_count_category', to='amulyaHerbal.tagname')),
            ],
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('day1_status', models.BooleanField(default=False)),
                ('day1_status_completed', models.DateTimeField(null=True)),
                ('day2_status', models.BooleanField(default=False)),
                ('day2_status_completed', models.DateTimeField(null=True)),
                ('day3_status', models.BooleanField(default=False)),
                ('day3_status_completed', models.DateTimeField(null=True)),
                ('success_bill_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amulyaHerb_activation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
