# Generated by Django 3.2.9 on 2022-07-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0006_activation_activationcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttagpivot',
            options={'ordering': ('product',)},
        ),
    ]
