# Generated by Django 3.2.9 on 2022-08-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0010_moneygenerate_moneygeneratecategory_useraccount_useraccounthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinhistory',
            options={'ordering': ('-created_at',)},
        ),
    ]
