# Generated by Django 3.2.9 on 2023-01-24 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amulyaHerbal', '0012_mcanumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('available_bv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mca_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amulyaHerbal_user_bv_mca_num', to='amulyaHerbal.mcanumber')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amulyaHerbal_user_bv', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
