# Generated by Django 3.2.9 on 2023-01-24 06:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0014_bvgenerator_bvrequest_howtocollectbv_instructioncreditsection_logdata_ordertakenforbv_userbvhistory_'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSignUP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mob', models.CharField(editable=False, max_length=15)),
                ('signup_token', models.CharField(default='gVvls5DVSw', editable=False, max_length=255, unique=True)),
                ('signup_data', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreSignUpOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mob', models.CharField(editable=False, max_length=15)),
                ('signup_token', models.CharField(editable=False, max_length=255, unique=True)),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='eKomv5fr', max_length=20),
        ),
    ]
