# Generated by Django 3.2.9 on 2023-08-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0018_auto_20230416_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='amulyaherbaluser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='amulyaherbaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='amulyaherbaluser',
            name='mob',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='amulyaherbaluser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='userDp'),
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='FHOZjUVQ', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='RL3K8TJRbP', editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='section_name',
            field=models.CharField(choices=[('Why Modicare', 'Why Modicare'), ('Learnings', 'Learnings'), ('Archivers', 'Archivers'), ('Events', 'Events')], default=None, max_length=50),
        ),
    ]
