# Generated by Django 3.2.9 on 2023-08-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0019_auto_20230819_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='egZwaPfD', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='Gnuc2WFBm4', editable=False, max_length=255, unique=True),
        ),
    ]
