# Generated by Django 3.2.9 on 2023-10-15 04:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0025_auto_20231014_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditTimer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post_click_wvdo_btn', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('pre_click_wvdo_btn', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='XCC8N5Wt', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='CwFwAOdouq', editable=False, max_length=255, unique=True),
        ),
    ]
