# Generated by Django 3.2.9 on 2023-10-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0027_auto_20231015_1105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreditTimer',
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='AdG5vv8v', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='7VDJsf6cRV', editable=False, max_length=255, unique=True),
        ),
    ]
