# Generated by Django 3.2.9 on 2023-10-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0029_auto_20231015_2042'),
        ('amulyaHerbal', '0030_auto_20231015_1920'),
    ]

    operations = [
    ]
