# Generated by Django 3.2.9 on 2023-10-16 11:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0031_merge_0029_auto_20231015_2042_0030_auto_20231015_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmulHerbalCreditTimer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post_click_wvdo_btn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pre_click_wvdo_btn', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='a5DrPOqq', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='qG55wBfhbO', editable=False, max_length=255, unique=True),
        ),
    ]
