# Generated by Django 3.2.9 on 2023-10-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amulyaHerbal', '0034_auto_20231016_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='w6waYV8u', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='326V280xdQ', editable=False, max_length=255, unique=True),
        ),
    ]
