# Generated by Django 3.2.9 on 2022-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinWorld', '0002_staticdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochuresections',
            name='brochure_image',
            field=models.ImageField(null=True, upload_to='PWBrochureSections'),
        ),
        migrations.AlterField(
            model_name='broucher',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='PWBookpdf'),
        ),
        migrations.AlterField(
            model_name='coinsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PWCoinSection'),
        ),
        migrations.AlterField(
            model_name='earningmodel',
            name='description_link',
            field=models.FileField(blank=True, null=True, upload_to='PWEarningModel'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='dp_list',
            field=models.ImageField(upload_to='PWORDImage'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='refer_earn',
            field=models.ImageField(upload_to='PWORDImage'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='view_all_offer',
            field=models.ImageField(upload_to='PWORDImage'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PWProductImages'),
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='section_image',
            field=models.ImageField(blank=True, null=True, upload_to='PWSectionImages'),
        ),
        migrations.AlterField(
            model_name='tagname',
            name='tagImage',
            field=models.ImageField(blank=True, null=True, upload_to='PWCategoryImages'),
        ),
    ]
