# Generated by Django 3.2.9 on 2023-01-24 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('proteinWorld', '0010_alter_coinhistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSignUP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mob', models.CharField(editable=False, max_length=15)),
                ('signup_token', models.CharField(default='CdXNW47Saq', editable=False, max_length=255, unique=True)),
                ('signup_data', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreSignUpOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mob', models.CharField(editable=False, max_length=15)),
                ('signup_token', models.CharField(editable=False, max_length=255, unique=True)),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='producttagpivot',
            options={'ordering': ('product',)},
        ),
    ]
