# Generated by Django 3.2.9 on 2023-01-24 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proteinWorld', '0011_auto_20230124_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='uqxfdTfywx', editable=False, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='MCANumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mca_number', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PW_mca_num', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
