# Generated by Django 3.2.9 on 2023-01-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinWorld', '0013_auto_20230124_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredcoinsforbill',
            name='min_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='jXj34klB', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='nyJhsCE3zh', editable=False, max_length=255, unique=True),
        ),
    ]
