# Generated by Django 3.2.9 on 2023-02-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinWorld', '0014_auto_20230130_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsection',
            name='section_type',
            field=models.CharField(choices=[('video_ads', 'video_ads'), ('recommended_apps', 'recommended_apps')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='SzxMfko4', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='E3JdK7kxkK', editable=False, max_length=255, unique=True),
        ),
    ]
