# Generated by Django 3.2.9 on 2023-10-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinWorld', '0023_auto_20231015_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='AEOThiK5', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='JAtM8DaZZt', editable=False, max_length=255, unique=True),
        ),
    ]
