# Generated by Django 3.2.9 on 2023-10-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proteinWorld', '0025_auto_20231015_2042'),
        ('proteinWorld', '0026_auto_20231015_1920'),
    ]

    operations = [
    ]
