# Generated by Django 3.2.9 on 2023-10-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinWorld', '0027_merge_0025_auto_20231015_2042_0026_auto_20231015_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='a0Fx4v2n', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='xT8VbUOWsM', editable=False, max_length=255, unique=True),
        ),
    ]
