# Generated by Django 3.2.9 on 2023-10-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proteinWorld', '0031_auto_20231016_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='aHAvRNt1', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='rZMeuXszD3', editable=False, max_length=255, unique=True),
        ),
    ]
