# Generated by Django 3.2.9 on 2022-06-04 04:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagHirarchy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='hhi.tagname')),
                ('subcategory', models.ManyToManyField(related_name='subcategory', to='hhi.TagName')),
            ],
            options={
                'ordering': ('category__serial_no',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productCode', models.CharField(max_length=30, unique=True)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.CharField(max_length=50)),
                ('colorDesc', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('loyalty', models.BooleanField(default=False, null=True)),
                ('ProductDescription', models.TextField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, default=0, max_length=50, null=True)),
                ('businessVolume', models.CharField(max_length=50, null=True)),
                ('personalVolume', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=True)),
                ('availability', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hhi.brand')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
