# Generated by Django 3.2.9 on 2022-06-04 04:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0002_product_taghirarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ProductImages')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productImages', to='hhi.product')),
            ],
        ),
        migrations.CreateModel(
            name='productTagPivot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='p_category', to='hhi.tagname')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hhi.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='P_subcategory', to='hhi.tagname')),
            ],
            options={
                'unique_together': {('product', 'category', 'subcategory')},
            },
        ),
    ]
