# Generated by Django 3.2.9 on 2022-06-04 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hhi.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hhi', '0004_cart_distributionpoint_usershippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('orderNumber', models.CharField(default=hhi.models.create_new_ref_number, max_length=30, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('distributionpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HHIDP', to='hhi.distributionpoint')),
                ('shippingDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='HHIUserShippingAddress', to='hhi.usershippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HHIOrderUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SectionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(choices=[('Why to use', 'Why to use'), ('Demo Videos', 'Demo Videos'), ('Business Opportunity', 'Business Opportunity'), ('Training Videos', 'Training Videos'), ('Motivational Videos', 'Motivational Videos'), ('Success Stories', 'Success Stories'), ('Testimonial Videos', 'Testimonial Videos'), ('About Modicare', 'About Modicare'), ('Become a Partner', 'Become a Partner'), ('Previous Events', 'Previous Events'), ('Upcoming Events', 'Upcoming Events'), ('Book Ticket', 'Book Ticket'), ('Broucher', 'Broucher'), ('Earning Model', 'Earning Model')], max_length=100, unique=True)),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='SectionImages')),
                ('section_name', models.CharField(choices=[('Why HHI', 'Why HHI'), ('Learnings', 'Learnings'), ('Archivers', 'Archivers'), ('Events', 'Events')], default=None, max_length=50)),
                ('section_type', models.CharField(choices=[('video', 'Video'), ('static', 'Static')], default=None, max_length=50, null=True)),
                ('section_data', models.URLField(blank=True, max_length=300, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('video_link', models.URLField(blank=True, max_length=300, null=True)),
                ('embed_link', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('section', models.CharField(choices=[('Why to use', 'Why to use'), ('Demo Videos', 'Demo Videos'), ('Business Opportunity', 'Business Opportunity'), ('Training Videos', 'Training Videos'), ('Motivational Videos', 'Motivational Videos'), ('Success Stories', 'Success Stories'), ('Testimonial Videos', 'Testimonial Videos')], default=None, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productQty', models.PositiveIntegerField()),
                ('PricePerPiece', models.CharField(max_length=30)),
                ('DiscountPerPiece', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HHIOrderProducts', to='hhi.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HHIProduct', to='hhi.product')),
            ],
        ),
    ]
