# Generated by Django 3.2.9 on 2022-06-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0005_order_orderproduct_sectiondata_videosections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hhiuser',
            old_name='vestige_user',
            new_name='hhi_user',
        ),
    ]
