# Generated by Django 3.2.9 on 2022-06-04 04:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0006_rename_vestige_user_hhiuser_hhi_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ad_type', models.CharField(max_length=255)),
                ('unit_id', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdSenseCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_list', models.IntegerField(default=10)),
                ('dp_list', models.IntegerField(default=10)),
                ('bill_list', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='OfferReferBgImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('view_all_offer', models.ImageField(upload_to='ORDImage')),
                ('dp_list', models.ImageField(upload_to='ORDImage')),
                ('refer_earn', models.ImageField(upload_to='ORDImage')),
            ],
        ),
    ]
