# Generated by Django 3.2.9 on 2022-06-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0011_staticdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochuresections',
            name='brochure_image',
            field=models.ImageField(null=True, upload_to='HHIBrochureSections'),
        ),
        migrations.AlterField(
            model_name='broucher',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='HHIBookpdf'),
        ),
        migrations.AlterField(
            model_name='coinsection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='HHICoinSection'),
        ),
        migrations.AlterField(
            model_name='earningmodel',
            name='description_link',
            field=models.FileField(blank=True, null=True, upload_to='HHIEarningModel'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='dp_list',
            field=models.ImageField(upload_to='HHIORDImage'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='refer_earn',
            field=models.ImageField(upload_to='HHIORDImage'),
        ),
        migrations.AlterField(
            model_name='offerreferbgimage',
            name='view_all_offer',
            field=models.ImageField(upload_to='HHIORDImage'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='HHIProductImages'),
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='section_image',
            field=models.ImageField(blank=True, null=True, upload_to='HHISectionImages'),
        ),
        migrations.AlterField(
            model_name='tagname',
            name='tagImage',
            field=models.ImageField(blank=True, null=True, upload_to='HHICategoryImages'),
        ),
    ]
