# Generated by Django 3.2.9 on 2022-08-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0017_activation_success_bill_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionpoint',
            name='dp_branch_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
