# Generated by Django 3.2.9 on 2023-10-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0029_auto_20230821_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='z1JBHNWS', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='AYpedthBQl', editable=False, max_length=255, unique=True),
        ),
    ]
