# Generated by Django 3.2.9 on 2023-10-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0033_auto_20231015_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='2sPyDlBh', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='Z3qGuYjkYt', editable=False, max_length=255, unique=True),
        ),
    ]
