# Generated by Django 3.2.9 on 2023-10-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0036_auto_20231015_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='IWURAGKS', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='Gbyrny8PKM', editable=False, max_length=255, unique=True),
        ),
    ]
