# Generated by Django 3.2.9 on 2023-10-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhi', '0050_auto_20231019_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='nI3ZAcPn', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='rfdYPtIjgP', editable=False, max_length=255, unique=True),
        ),
    ]
