# Generated by Django 3.2.9 on 2021-12-05 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0007_alter_orderproduct_productqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='averageVolume',
        ),
        migrations.AddField(
            model_name='product',
            name='personalVolume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderProducts', to='ecomApp.order'),
        ),
    ]
