# Generated by Django 3.2.9 on 2021-12-05 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0009_auto_20211205_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distributionpoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecomApp.distributionpoint'),
        ),
    ]
