# Generated by Django 3.2.9 on 2021-12-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0013_order_shippingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='loyalty',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
