# Generated by Django 3.2.9 on 2021-12-24 02:47

from django.db import migrations, models
import ecomApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0015_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='savelater',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderNumber',
            field=models.CharField(default=ecomApp.models.create_new_ref_number, max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('product', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='producttagpivot',
            unique_together={('product', 'category', 'subcategory')},
        ),
    ]
