# Generated by Django 3.2.9 on 2021-12-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0017_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
