# Generated by Django 3.2.9 on 2021-12-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0018_userotp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(upload_to='pdfFiles')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_order', to='ecomApp.order')),
            ],
        ),
    ]
