# Generated by Django 3.2.9 on 2022-01-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0019_billformat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
