# Generated by Django 3.2.9 on 2022-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0020_alter_product_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionpoint',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
