# Generated by Django 3.2.9 on 2022-01-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0021_auto_20220119_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionpoint',
            name='cityName',
            field=models.CharField(max_length=100, null=True),
        ),
         migrations.AddField(
            model_name='distributionpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='distributionpoint',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
