# Generated by Django 3.2.9 on 2022-01-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0023_auto_20220119_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionpoint',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
