# Generated by Django 3.2.9 on 2022-01-23 11:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0025_auto_20220120_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('video_link', models.URLField(blank=True, max_length=300, null=True)),
                ('embed_link', models.URLField(blank=True, max_length=750, null=True)),
                ('section', models.CharField(choices=[('why_to_use', 'Why to use'), ('demo_videos', 'Demo Videos'), ('business_opportunity', 'Business Opportunity'), ('training_videos', 'Training Videos'), ('motivational_videos', 'Motivational Videos'), ('success_stories', 'Success Stories'), ('testimonial_videos', 'Testimonial Videos')], default=None, max_length=200, null=True)),
            ],
        )
    ]
