# Generated by Django 3.2.9 on 2022-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0026_auto_20220123_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosections',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
