# Generated by Django 3.2.9 on 2022-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0027_auto_20220123_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosections',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
