# Generated by Django 3.2.9 on 2022-01-24 03:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0029_auto_20220123_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='SectionImages')),
                ('section_type', models.CharField(choices=[('why_modicare', 'Why Modicare'), ('learnings', 'Learnings'), ('archivers', 'Archivers'), ('events', 'Events')], default=None, max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
