# Generated by Django 3.2.9 on 2022-01-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0030_auto_20220124_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectiondata',
            old_name='section_type',
            new_name='section_name',
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='title',
            field=models.CharField(choices=[('why_to_use', 'Why to use'), ('demo_videos', 'Demo Videos'), ('business_opportunity', 'Business Opportunity'), ('training_videos', 'Training Videos'), ('motivational_videos', 'Motivational Videos'), ('success_stories', 'Success Stories'), ('testimonial_videos', 'Testimonial Videos')], max_length=100),
        ),
    ]
