# Generated by Django 3.2.9 on 2022-01-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0031_auto_20220124_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondata',
            name='section_type',
            field=models.CharField(choices=[('video', 'Video'), ('static', 'Static')], default=None, max_length=50, null=True),
        ),
    ]
