# Generated by Django 3.2.9 on 2022-01-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0032_sectiondata_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectiondata',
            name='section_data',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
