# Generated by Django 3.2.9 on 2022-01-24 04:47

from django.db import migrations, models
import ecomApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0034_auto_20220124_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.CharField(default=ecomApp.models.create_new_user_id, max_length=20, unique=True),
        ),
    ]
