# Generated by Django 3.2.9 on 2022-02-11 10:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0037_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('privacy_policy', models.TextField()),
                ('about_us', models.TextField()),
                ('terms_and_condition', models.TextField()),
            ],
        ),
    ]
