# Generated by Django 3.2.9 on 2022-02-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0038_staticdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionpoint',
            name='dp_type',
            field=models.CharField(choices=[('Teams Builders Super Store', 'Teams Builders Super Store'), ('Team Builders Success Center (MSC)', 'Team Builders Success Center (MSC)'), ('Teams Builders Lifestyle Center', 'Teams Builders Lifestyle Center'), ('Teams Builders Access Point (TFS Store)', 'Teams Builders Access Point (TFS Store)'), ('DISTRIBUTION POINTS (DPS)', 'DISTRIBUTION POINTS (DPS)')], default='DISTRIBUTION POINTS (DPS)', max_length=50, null=True),
        ),
    ]
