# Generated by Django 3.2.9 on 2022-02-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0039_distributionpoint_dp_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tagname',
            options={'ordering': ('serial_no',)},
        ),
        migrations.AddField(
            model_name='tagname',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
