# Generated by Django 3.2.9 on 2022-02-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0040_auto_20220223_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagname',
            name='serial_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
