# Generated by Django 3.2.9 on 2022-02-27 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0042_auto_20220226_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ad_type', models.CharField(max_length=255)),
                ('unit_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='videosections',
            options={'ordering': ('-created_at',)},
        ),
    ]
