# Generated by Django 3.2.9 on 2022-02-27 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0043_auto_20220227_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferReferBgImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('view_all_offer', models.ImageField(upload_to='ORDImage')),
                ('dp_list', models.ImageField(upload_to='ORDImage')),
                ('refer_earn', models.ImageField(upload_to='ORDImage')),
            ],
        ),
    ]
