# Generated by Django 3.2.9 on 2022-02-28 04:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0044_offerreferbgimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSenseCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_list', models.IntegerField(default=10)),
                ('dp_list', models.IntegerField(default=10)),
                ('bill_list', models.IntegerField(default=10)),
            ],
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='section_name',
            field=models.CharField(choices=[('Why Modicare', 'Why Modicare'), ('Learnings', 'Learnings'), ('Archivers', 'Archivers'), ('Events', 'Events')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='title',
            field=models.CharField(choices=[('Why to use', 'Why to use'), ('Demo Videos', 'Demo Videos'), ('Business Opportunity', 'Business Opportunity'), ('Training Videos', 'Training Videos'), ('Motivational Videos', 'Motivational Videos'), ('Success Stories', 'Success Stories'), ('Testimonial Videos', 'Testimonial Videos'), ('About Modicare', 'About Modicare'), ('Become a Partner', 'Become a Partner'), ('Previous Events', 'Previous Events'), ('Upcoming Events', 'Upcoming Events'), ('Book Ticket', 'Book Ticket')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='videosections',
            name='section',
            field=models.CharField(choices=[('Why to use', 'Why to use'), ('Demo Videos', 'Demo Videos'), ('Business Opportunity', 'Business Opportunity'), ('Training Videos', 'Training Videos'), ('Motivational Videos', 'Motivational Videos'), ('Success Stories', 'Success Stories'), ('Testimonial Videos', 'Testimonial Videos')], default=None, max_length=200, null=True),
        ),
    ]
