# Generated by Django 3.2.9 on 2022-03-01 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0045_auto_20220228_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionpoint',
            name='dp_type',
            field=models.CharField(choices=[('Modicare Super Store', 'Modicare Super Store'), ('Modicare Success Center (MSC)', 'Modicare Success Center (MSC)'), ('Modicare Lifestyle Center', 'Modicare Lifestyle Center'), ('Modicare Access Point (TFS Store)', 'Modicare Access Point (TFS Store)'), ('DISTRIBUTION POINTS (DPS)', 'DISTRIBUTION POINTS (DPS)')], default='DISTRIBUTION POINTS (DPS)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='title',
            field=models.CharField(choices=[('Why to use', 'Why to use'), ('Demo Videos', 'Demo Videos'), ('Business Opportunity', 'Business Opportunity'), ('Training Videos', 'Training Videos'), ('Motivational Videos', 'Motivational Videos'), ('Success Stories', 'Success Stories'), ('Testimonial Videos', 'Testimonial Videos'), ('About Modicare', 'About Modicare'), ('Become a Partner', 'Become a Partner'), ('Previous Events', 'Previous Events'), ('Upcoming Events', 'Upcoming Events'), ('Book Ticket', 'Book Ticket'), ('Broucher', 'Broucher'), ('Earning Model', 'Earning Model')], max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Broucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Odia', 'Odia'), ('Bengali', 'Bengali'), ('Tamil', 'Tamil')], max_length=255)),
                ('book_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomApp.tagname')),
            ],
        ),
    ]
