# Generated by Django 3.2.9 on 2022-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0046_auto_20220301_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='broucher',
            name='book_pdf',
            field=models.FileField(blank=True, null=True, upload_to='Bookpdf'),
        ),
    ]
