# Generated by Django 3.2.9 on 2022-03-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0047_broucher_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broucher',
            name='category',
        ),
    ]
