# Generated by Django 3.2.9 on 2022-03-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0048_remove_broucher_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broucher',
            name='language',
        ),
        migrations.AddField(
            model_name='broucher',
            name='brochure_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='broucher',
            name='book_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
