# Generated by Django 3.2.9 on 2022-03-04 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0049_auto_20220304_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarningModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('earning_amount', models.CharField(max_length=255)),
                ('description_link', models.FileField(blank=True, null=True, upload_to='EarningModel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='broucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
