# Generated by Django 3.2.9 on 2022-03-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0051_brochuresections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broucher',
            name='brochure_name',
        ),
        migrations.AddField(
            model_name='broucher',
            name='brochure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ecomApp.brochuresections'),
        ),
    ]
