# Generated by Django 3.2.9 on 2022-03-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0053_auto_20220304_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brochuresections',
            name='brochure_image',
            field=models.ImageField(null=True, upload_to='BrochureSections'),
        ),
    ]
