# Generated by Django 3.2.9 on 2022-03-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0054_alter_brochuresections_brochure_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='app_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
