# Generated by Django 3.2.9 on 2022-04-13 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0059_coindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredcoinsforbill',
            name='spinner_required_coins',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requiredcoinsforbill',
            name='required_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='coinHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coin', models.IntegerField()),
                ('type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
