# Generated by Django 3.2.9 on 2022-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0060_auto_20220413_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinhistory',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
