# Generated by Django 3.2.9 on 2022-04-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0061_coinhistory_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_mob_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
