# Generated by Django 3.2.9 on 2022-06-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0065_dailycheckin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycheckin',
            name='coin',
        ),
        migrations.RemoveField(
            model_name='dailycheckin',
            name='status',
        ),
    ]
