# Generated by Django 3.2.9 on 2022-07-07 04:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0069_auto_20220707_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('required_product', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_count_category', to='ecomApp.tagname')),
            ],
        ),
    ]
