# Generated by Django 3.2.9 on 2022-07-07 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0071_delete_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('success_bill_no', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_product_category', to='ecomApp.tagname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modicare_activation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
