# Generated by Django 3.2.9 on 2022-07-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0073_auto_20220707_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='day1_status_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activation',
            name='day2_status_completed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='activation',
            name='day3_status_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
