# Generated by Django 3.2.9 on 2022-07-10 04:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0074_auto_20220707_1544'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttagpivot',
            options={'ordering': ('product',)},
        ),
        migrations.AddField(
            model_name='activation',
            name='success_bill_lists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), null=True, size=None),
        ),
    ]
