# Generated by Django 3.2.9 on 2022-07-10 10:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0075_auto_20220710_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='success_bill_lists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), default=list, null=True, size=None),
        ),
    ]
