# Generated by Django 3.2.9 on 2022-08-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0078_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
