# Generated by Django 3.2.9 on 2022-08-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0080_useraccounthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccounthistory',
            name='type',
            field=models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=25),
        ),
    ]
