# Generated by Django 3.2.9 on 2022-08-14 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0081_useraccounthistory_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinhistory',
            options={'ordering': ('-created_at',)},
        ),
    ]
