# Generated by Django 3.2.9 on 2022-11-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0082_alter_coinhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='view_all_offer',
            field=models.TextField(null=True),
        ),
    ]
