# Generated by Django 3.2.9 on 2022-11-15 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0085_userbv'),
    ]

    operations = [
        migrations.CreateModel(
            name='BVRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('requested_bv', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('peding', 'pending'), ('success', 'success'), ('rejected', 'rejected')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mca_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomApp.mcanumber')),
            ],
        ),
    ]
