# Generated by Django 3.2.9 on 2022-11-15 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0086_bvrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcanumber',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userbv',
            name='mca_number',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecomApp.mcanumber'),
        ),
    ]
