# Generated by Django 3.2.9 on 2022-11-15 15:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0087_auto_20221115_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('rejected', 'rejected')], max_length=30),
        ),
        migrations.CreateModel(
            name='UserBVHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bv_number', models.IntegerField(default=0)),
                ('transaction_type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mca_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomApp.mcanumber')),
            ],
        ),
    ]
