# Generated by Django 3.2.9 on 2022-11-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0089_auto_20221117_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbvhistory',
            old_name='transaction_type',
            new_name='transaction',
        ),
    ]
