# Generated by Django 3.2.9 on 2022-11-20 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0090_rename_transaction_type_userbvhistory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcanumber',
            name='mca_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='UserBVRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mca_number', models.IntegerField()),
                ('requested_bv', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('success', 'success'), ('rejected', 'rejected')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
