# Generated by Django 3.2.9 on 2022-11-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0094_alter_userbvhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbv',
            name='mca_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomApp.mcanumber'),
        ),
    ]
