# Generated by Django 3.2.9 on 2022-11-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0095_alter_userbv_mca_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsection',
            name='section_type',
            field=models.CharField(choices=[('video_ads', 'video_ads'), ('recommended_apps', 'recommended_apps')], max_length=255, null=True),
        ),
    ]
