# Generated by Django 3.2.9 on 2022-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0096_coinsection_section_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredcoinsforbill',
            name='min_items',
            field=models.IntegerField(default=0),
        ),
    ]
