# Generated by Django 3.2.9 on 2022-12-12 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0097_requiredcoinsforbill_min_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='BVGenerator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('max_bv_per_day', models.IntegerField(default=1)),
                ('min_products', models.IntegerField(default=0)),
                ('bv_on_success', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
