# Generated by Django 3.2.9 on 2022-12-13 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0099_ordertakenforbv'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertakenforbv',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
