# Generated by Django 3.2.9 on 2022-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0100_ordertakenforbv_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='requested_bv',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userbv',
            name='available_bv',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userbvhistory',
            name='bv_number',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userbvrequesthistory',
            name='requested_bv',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
