# Generated by Django 3.2.9 on 2022-12-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0102_instructioncreditsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructioncreditsection',
            name='type',
            field=models.CharField(choices=[('marquee', 'marquee'), ('instruction', 'instruction')], default='instruction', max_length=20),
        ),
    ]
