# Generated by Django 3.2.9 on 2022-12-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0103_instructioncreditsection_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticdata',
            name='how_to_collect_bv',
            field=models.TextField(null=True),
        ),
    ]
