# Generated by Django 3.2.9 on 2022-12-22 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0104_staticdata_how_to_collect_bv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAllOffers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offer_name', models.CharField(max_length=255)),
                ('offer_file', models.FileField(blank=True, null=True, upload_to='viewOffer')),
                ('offer_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
