# Generated by Django 3.2.9 on 2022-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0105_viewalloffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewalloffers',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('pdf', 'pdf')], default='image', max_length=20),
        ),
    ]
