# Generated by Django 3.2.9 on 2022-12-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0106_viewalloffers_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='VKoHj6tc', max_length=20),
        ),
        migrations.AddField(
            model_name='userbvhistory',
            name='request_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
