# Generated by Django 3.2.9 on 2022-12-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0107_auto_20221223_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbvhistory',
            name='request_id',
        ),
        migrations.AddField(
            model_name='userbvrequesthistory',
            name='request_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='WYIT8Sgn', max_length=20),
        ),
    ]
