# Generated by Django 3.2.9 on 2023-01-02 17:14

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0108_auto_20221223_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToCollectBV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('youtube_link', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='qmYrOuIe', max_length=20),
        ),
    ]
