# Generated by Django 3.2.9 on 2023-01-10 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0111_auto_20230110_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreSignUpOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('mob', models.CharField(editable=False, max_length=15)),
                ('signup_token', models.CharField(editable=False, max_length=255, unique=True)),
                ('otp', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='UJwTR26V', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='7OMVz20Afy', editable=False, max_length=255, unique=True),
        ),
    ]
