# Generated by Django 3.2.9 on 2023-01-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0113_auto_20230110_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='function',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='JRfOiXH1', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='X60W1dOX3r', editable=False, max_length=255, unique=True),
        ),
    ]
