# Generated by Django 3.2.9 on 2023-01-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0114_auto_20230110_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='b80SStSg', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='fsVSLCuVwh', editable=False, max_length=255, unique=True),
        ),
    ]
