# Generated by Django 3.2.9 on 2023-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0117_auto_20230416_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='modicareuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modicareuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='modicareuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modicareuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modicareuser',
            name='mob',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='modicareuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='userDp'),
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='uyEB2v9s', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='yUXFSVB8Be', editable=False, max_length=255, unique=True),
        ),
    ]
