# Generated by Django 3.2.9 on 2023-08-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0119_auto_20230821_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='bRj16TV7', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='Hmq6amsj0B', editable=False, max_length=255, unique=True),
        ),
    ]
