# Generated by Django 3.2.9 on 2023-10-14 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0120_auto_20230821_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='sMwg5Shw', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='NbOOp3rt84', editable=False, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bank_name', models.CharField(max_length=50, null=True)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=30)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomApp.modicareuser')),
            ],
        ),
    ]
