# Generated by Django 3.2.9 on 2023-10-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0127_auto_20231015_2042'),
        ('ecomApp', '0128_auto_20231015_1920'),
    ]

    operations = [
    ]
