# Generated by Django 3.2.9 on 2022-04-27 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import vestige.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vestige', '0004_cart_usershippingaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('orderNumber', models.CharField(default=vestige.models.create_new_ref_number, max_length=30, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('distributionpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vestigeDP', to='vestige.distributionpoint')),
                ('shippingDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vestigeUserShippingAddress', to='vestige.usershippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vestigeOrderUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
