# Generated by Django 3.2.9 on 2022-04-27 10:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vestige', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('productQty', models.PositiveIntegerField()),
                ('PricePerPiece', models.CharField(max_length=30)),
                ('DiscountPerPiece', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vestigeOrderProducts', to='vestige.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vestigeProduct', to='vestige.product')),
            ],
        ),
    ]
