# Generated by Django 3.2.9 on 2022-06-03 06:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vestige', '0007_sectiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('video_link', models.URLField(blank=True, max_length=300, null=True)),
                ('embed_link', models.TextField(blank=True, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('section', models.CharField(choices=[('Why to use', 'Why to use'), ('Demo Videos', 'Demo Videos'), ('Business Opportunity', 'Business Opportunity'), ('Training Videos', 'Training Videos'), ('Motivational Videos', 'Motivational Videos'), ('Success Stories', 'Success Stories'), ('Testimonial Videos', 'Testimonial Videos')], default=None, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='sectiondata',
            name='section_name',
            field=models.CharField(choices=[('Why Vestige', 'Why Vestige'), ('Learnings', 'Learnings'), ('Archivers', 'Archivers'), ('Events', 'Events')], default=None, max_length=50),
        ),
    ]
