# Generated by Django 3.2.9 on 2022-06-03 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vestige', '0008_auto_20220603_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ad_type', models.CharField(max_length=255)),
                ('unit_id', models.CharField(max_length=255)),
                ('app_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdSenseCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product_list', models.IntegerField(default=10)),
                ('dp_list', models.IntegerField(default=10)),
                ('bill_list', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='BrochureSections',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('brochure_name', models.CharField(max_length=255, null=True, unique=True)),
                ('brochure_image', models.ImageField(null=True, upload_to='BrochureSections')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EarningModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('earning_amount', models.CharField(max_length=255)),
                ('description_link', models.FileField(blank=True, null=True, upload_to='EarningModel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferReferBgImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('view_all_offer', models.ImageField(upload_to='ORDImage')),
                ('dp_list', models.ImageField(upload_to='ORDImage')),
                ('refer_earn', models.ImageField(upload_to='ORDImage')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('coin', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VestigeUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Broucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('book_name', models.CharField(max_length=255, null=True)),
                ('book_pdf', models.FileField(blank=True, null=True, upload_to='Bookpdf')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('brochure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vestige.brochuresections')),
            ],
        ),
    ]
