# Generated by Django 3.2.9 on 2022-08-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestige', '0019_activation_success_bill_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionpoint',
            name='dp_branch_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='distributionpoint',
            name='dp_type',
            field=models.CharField(choices=[('Vestige Super Store', 'Vestige Super Store'), ('Vestige Success Center (MSC)', 'Vestige Success Center (MSC)'), ('Vestige Lifestyle Center', 'Vestige Lifestyle Center'), ('Vestige Access Point (TFS Store)', 'Vestige Access Point (TFS Store)'), ('DISTRIBUTION POINTS (DPS)', 'DISTRIBUTION POINTS (DPS)')], default='DISTRIBUTION POINTS (DPS)', max_length=50, null=True),
        ),
    ]
