# Generated by Django 3.2.9 on 2022-08-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestige', '0020_auto_20220801_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
