# Generated by Django 3.2.9 on 2023-01-18 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vestige', '0025_auto_20230118_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='6zNxupTzsV', editable=False, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='UserBVRequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_id', models.CharField(max_length=20, null=True)),
                ('mca_number', models.IntegerField()),
                ('requested_bv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('rejected', 'rejected')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vestige_user_bv_request_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBVHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bv_number', models.DecimalField(decimal_places=2, max_digits=5)),
                ('transaction', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mca_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestige_bv_history_mca_num', to='vestige.mcanumber')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vestige_user_bv_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BVRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('request_id', models.CharField(default='DgaVKQnM', max_length=20)),
                ('requested_bv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('rejected', 'rejected')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mca_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vestige_bv_mca_num', to='vestige.mcanumber')),
            ],
        ),
    ]
