# Generated by Django 3.2.9 on 2023-01-18 10:58

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vestige', '0027_auto_20230118_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowToCollectBV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('youtube_link', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, null=True, size=None)),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionCreditSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('marquee', 'marquee'), ('instruction', 'instruction')], default='instruction', max_length=20)),
                ('instruction', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ViewAllOffers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('offer_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'image'), ('pdf', 'pdf')], default='image', max_length=20)),
                ('offer_file', models.FileField(blank=True, null=True, upload_to='viewOffer')),
                ('offer_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='pUqu4CBT', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='yPfWZEHlEH', editable=False, max_length=255, unique=True),
        ),
    ]
