# Generated by Django 3.2.9 on 2023-01-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestige', '0030_auto_20230118_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='JsCTdWMp', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='mkgBD0mxqP', editable=False, max_length=255, unique=True),
        ),
    ]
