# Generated by Django 3.2.9 on 2023-10-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestige', '0037_auto_20231014_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='1bloXcsH', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='MWnLc7ElqQ', editable=False, max_length=255, unique=True),
        ),
    ]
