# Generated by Django 3.2.9 on 2023-10-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vestige', '0039_auto_20231015_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvrequest',
            name='request_id',
            field=models.CharField(default='EVAdB3Tq', max_length=20),
        ),
        migrations.AlterField(
            model_name='presignup',
            name='signup_token',
            field=models.CharField(default='Dk5jywDQth', editable=False, max_length=255, unique=True),
        ),
    ]
