# Generated by Django 3.2.9 on 2022-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsbuilders', '0002_auto_20220621_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsbuildersuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
