# Generated by Django 3.2.9 on 2022-06-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsbuilders', '0003_teamsbuildersuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamsbuildersuser',
            name='age',
        ),
        migrations.AddField(
            model_name='teamsbuildersuser',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
