# Generated by Django 3.2.9 on 2022-07-15 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teamsbuilders.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teamsbuilders', '0005_referecehandler'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reference_number', models.CharField(default=teamsbuilders.models.random_alphanum, max_length=25, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_referral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
