# Generated by Django 3.2.9 on 2022-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsbuilders', '0007_useractivepaymentdetails_userbankaccount_userpaytmwallet_userupi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_number',
            field=models.CharField(max_length=30),
        ),
    ]
