# Generated by Django 3.2.9 on 2022-08-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamsbuilders', '0010_homepagevideos'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivepaymentdetails',
            name='default_payment',
            field=models.CharField(choices=[('bank_account', 'bank_account'), ('upi', 'upi'), ('paytm_wallet', 'paytm_wallet')], default='bank_account', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='useractivepaymentdetails',
            unique_together={('user', 'bank_account')},
        ),
    ]
